### ISSUE TITLE
Exception thrown !

### ISSUE THREAD

**Issue by pcouderc12** [kdw2060/bose-soundtouch-alt-interface#1]
ous@pcouderc:~/projets/bose/Bose-Soundtouch-Alt-Interface$ node server.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/nous/projets/bose/Bose-Soundtouch-Alt-Interface/server.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Please note that I have installed node.js and npm with apt install on debian buster.
Thanks for help
PC

**Comment by kdw2060** [comment]
did you execute the 'npm install' command? Sounds like you might have missed that step.

**Comment by pcouderc12** [comment]
No ! My mistake. I thought that "install" was done by "apt install". Thank ou it is better now !

**Comment by pcouderc12** [comment]
now I get : 
nous@pcouderc:~/projets/bose/Bose-Soundtouch-Alt-Interface$ node server.js
/home/nous/projets/bose/Bose-Soundtouch-Alt-Interface/server.js:48
  let ethernet = os.networkInterfaces().Ethernet.length;
                                                ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/home/nous/projets/bose/Bose-Soundtouch-Alt-Interface/server.js:48:49)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
...

**Comment by pcouderc12** [comment]
node.js  release is 19.15.2

**Comment by kdw2060** [comment]
I'm figuring that code bit that autodiscovers the ip adress out as I go too. Can't tell why it doesn't work on your device without access to it.

If you know the ip-address of the device you're running my app on, then comment out lines 40-50 in server.js and change line 39 into `let deviceIP= 'your ip'`

**Comment by pcouderc12** [comment]
Thank you, I do not know node.js but I try to debug it...

**Comment by pcouderc12** [comment]
Fine, it works not so bad...
1- I succes to get dinner ready. It is fine in these times of coronavirus : we can eat at least instead of going out...
2- But I do not success to change the volume.. It seems to change but dinner's volume does not change
3- I cannot get any station playing : I get  a message : 
error: StatusCodeError: 500 - "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><errors deviceID=\"304511AD6755\"><error value=\"1005\" name=\"UNKNOWN_SOURCE_ERROR\" severity=\"Unknown\">1005</error></errors>"
4- For deviceIP discovery, I am on linux with no eth0, only lo an wlp1s0 (wifi). I suggest a loop on all interfaces, and keep, the first starting with "e" or "w" and 127.0.0.1 if none. I do not know node.js so I cannot suggest a patch.
Thank you  very much for this  fine app.
pierre at couderc.eu

**Comment by pcouderc12** [comment]
Mmm, I do no t think I wanted to close it...
